# File: step-env-build-copy-kv-settings.yml@templates
# --------------------------------------
#   - template: step-env-build-copy-kv-settings.yml@templates
#     parameters:
#       AppAbbrev: '${{ parameters.AppAbbrev }}'
#       VNextRegion: '${{ parameters.VNextRegion}}'
#       DeploySlot: '${{ parameters.DeploySlot }}'
#       DeploySlotAbbrev: '$(cicd-deployslot-abbrev)'
#       KeyVaultFrom: 'lexprd-uae-vnext-cicd'
#       KeyVaultTo: 'lexprd-uae-vnext-cicd' # Can be blank, defaults to KeyVaultFrom
#       VerNoFrom: '1.0.0'
#       VerNoTo: '1.0.1'
#       ModuleName: 'DevopsUtils'
# ================================
#    [version]$AppVerFrom = '1.0.0',
#    [version]$AppVerTo = '1.0.1',
#    [string]$ModuleName = 'DevopsUtils'

# --------------------------------------
parameters:
# ----------------------------------------------------------
- name: VNextRegion
  type: string
- name: AppAbbrev
  type: string
- name: DeploySlot
  type: string
  values:
    - staging
    - production
- name: DeploySlotAbbrev
  type: string
  values:
    - stg
    - prd
  default:
- name: KeyVaultFrom
  type: string
- name: KeyVaultTo
  type: string
  default: ''
- name: VerNoFrom
  type: string
- name: VerNoTo
  type: string
- name: ModuleName
  type: string
  default: 'DevopsUtils'
- name: ShowParams
  type: boolean
  default: false
# ----------------------------------------------------------
steps:
- task: PowerShell@2
  displayName: '[debug]: step-env-build-copy-kv-settings'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host '-----Template: step-env-build-copy-kv-settings-----'
      Write-Host ' VNextRegion     : ${{ parameters.VNextRegion }}'
      Write-Host ' AppAbbrev       : ${{ parameters.AppAbbrev }}'
      Write-Host ' DeploySlot      : ${{ parameters.DeploySlot }}'
      Write-Host ' DeploySlotAbbrev: ${{ parameters.DeploySlotAbbrev }}'
      Write-Host ' KeyVaultFrom    : ${{ parameters.KeyVaultFrom }}'
      Write-Host ' KeyVaultTo      : ${{ parameters.KeyVaultTo }}'
      Write-Host ' VerNoFrom       : ${{ parameters.VerNoFrom }}'
      Write-Host ' VerNoTo         : ${{ parameters.VerNoTo }}'
      Write-Host ' ModuleName      : ${{ parameters.ModuleName }}'
    showWarnings: true
    pwsh: true
  enabled: ${{ parameters.ShowParams }}
# ----------------------------------------------------------
- template: step-Search-Files-Path.yml@templates
  parameters:
    FileNames:
    - Name: 'CloneVNextKvAppSettings.ps1'
      VarName: 'Clone.Kv.AppSettings.File.Path'
    RootFolder: $(Build.SourcesDirectory)
    ReturnFullPath: true
# ----------------------------------------------------------
- task: AzurePowerShell@5
  displayName: 'Clone KV AppSettings'
  inputs:
    azureSubscription: '${{ parameters.SvcAccount }}'
    ScriptType: 'FilePath'
    ScriptPath: '$(Clone.Kv.AppSettings.File.Path)'
    ScriptArguments: >
      -KvNameFrom '${{ parameters.KeyVaultFrom }}'
      -KvNameTo '${{ parameters.KeyVaultTo }}'
      -AppVerFrom '${{ parameters.VerNoFrom }}'
      -AppVerTo '${{ parameters.VerNoTo }}'
      -ModuleName '${{ parameters.ModuleName }}'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
  enabled: ${{ parameters.RunScript }}
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    VNEXT_REGION: ${{ parameters.VNextRegion }}
    VNEXT_DEPLOY_SLOT: ${{ parameters.DeploySlot }}
    VNEXT_APP_ABBREV: ${{ parameters.AppAbbrev }}
    VNEXT_RG: 'lexprd=${{ lower(parameters.VNextRegion) }}-vnext'
#      AZDO_SERVICE_CONNECTIONS_FILEPATH: $(AzDoServiceConnections.File.Path)
#      AZDO_SERVICE_CONNECTION_NAME: '${{ parameters.SvcAccount }}'
